### PR TITLE
ported to mc 1.17.1

### PR DESCRIPTION
**Pull request by maxheyn**
Hey, I liked this mod but wanted to use it on my 1.17.1 server. I took the liberty of porting it myself. Hope this is useful to you.

Also, just something to consider, but on my server I want anyone to be able to use the /slap commands, so maybe consider adding a way in a config file to allow admins to set the permission level in [Register.java ](https://github.com/kalkronline/slapmap/blob/master/src/main/java/online/kalkr/slapmap/action/Register.java) to 0 for their players.

### CODE REVIEW

**Comment by maxheyn** [comment]
bump

**Comment by kalkronline** [comment]
hi thanks for the work :)
i have a build working on 1.17 right now, but improvement in my strengths as a developer and (massive) underlying problems with the mod have forced me to not release any updates yet
im planning on a rewrite with a new config system and additional tooling in moderating images for more non-moderator use, which should be out in a week or two
im sorry for a lack of communication, this isn't my proudest project and i didn't realize that people cared about it. again, i appreciate you reaching out to me, it really makes me happy that people value my very poorly designed mod. :)

**Comment by maxheyn** [comment]
No worries mate. I found this mod on [the big list of serverside mods](https://github.com/comp500/fabric-serverside-mods) and wanted to play around with mods on my testing server to get ready to release it when 1.18.1 comes out. I needed something to practice updating incase other mods don't update fast enough for me to release the server, and this was the perfect candidate for it. I also really like it, there's no other mod out there right now (that I know of, anyway) that does this. It's a good mod :)

**Comment by BrekiTomasson** [comment]
@maxheyn Since you're not allowing issues in your repo, I'm commenting here. I should point out that your version of slapmap allows people to endlessly create amethyst shards, at least when I'm testing it (so it might be a conflict with another mod).

Basically, create a slap, place it, and then punch it out with your fists, and it drops the map and an amethyst shard for some reason.

Also, if you're already making changes to the mod, might I suggest that it defaults to some reasonable height/width if nothing is stated? Say, maybe it figures out which edge of the image given is the longest and then does `width=2` if it's an image in landscape orientation or `height=2` if it's an image in portrait orientation?

**Pull request closed without merging**
